In [1]:
print("hello")

hello


In [2]:
print("hello world")

hello world


In [ ]:
# Basics of Python Programming

In [2]:
%pip install pandas

   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/10.0 MB 2.2 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/10.0 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/10.0 MB 3.1 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/10.0 MB 3.3 MB/s eta 0:00:03
   ---------------- ----------------------- 4.2/10.0 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/10.0 MB 3.8 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/10.0 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/10.0 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 4.5 MB/s  0:00:02
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ---------------

In [3]:
import pandas as pd

# Heading 1
## Heading 2
### Heading 3


1. List 1
2. List 2
3. List 3

- List 1
- List 2
- List 3

$ y^3 $

$$
H^5
$$

$$
\begin{aligned}
\frac{arg1}{arg2} \\
N^6 \\
P_o \\
B_{ij} \\
\sqrt[n]{arg1}
\end{aligned}
$$

In [4]:
#Python Functions

In [5]:
#def function_name():
 #   // code of line

In [4]:
def HelloWorld():
    print("hello world, this is my first function")

In [5]:
HelloWorld()

hello world, this is my first function


In [6]:
def add(x,y):
    return x+y

In [7]:
add(10,20)

30

In [8]:
type(HelloWorld())

hello world, this is my first function


NoneType

In [9]:
type(None)

NoneType

In [10]:
#Types and sequence

In [11]:
# numbers
a = 1
b = 1.0
c = -999

In [12]:
#String
a = '1'

In [13]:
type(a)

str

In [14]:
#List
l = []
l = list()

In [15]:
#Access List Items
l = [1,2,3,4,5]

In [16]:
l[3]

4

In [17]:
l[-1]

5

In [18]:
l[2:4]

[3, 4]

In [19]:
l = [1,'strings',[1,2,3]]

In [20]:
print(l)

[1, 'strings', [1, 2, 3]]


In [22]:
for i in l:
    print(i)

1
strings
[1, 2, 3]


In [24]:
for i in range(len(l)):
    print(l[i])

1
strings
[1, 2, 3]


In [25]:
#Tuples
t = ('tree','moon','star')

In [26]:
type(t)

tuple

In [27]:
t[0]

'tree'

In [28]:
t[0] = 'cloud'

TypeError: 'tuple' object does not support item assignment

In [29]:
t = ('apple',)

In [30]:
len(t)

1

In [31]:
#Dictonaries
d ={'a':1,'b':2}

In [32]:
d['a']

1

In [33]:
d['b']

2

In [34]:
d['c']=3

In [35]:
d

{'a': 1, 'b': 2, 'c': 3}

In [36]:
d.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [37]:
d.keys()

dict_keys(['a', 'b', 'c'])

In [38]:
d.values()

dict_values([1, 2, 3])

In [5]:
#Numpy in Python
import numpy as np

A = np.array([[1,2,5],[6,8,3]])
B = np.array([3,4,6])

In [6]:
A


array([[1, 2, 5],
       [6, 8, 3]])

In [7]:
B

array([3, 4, 6])

In [8]:
np.add(A,B)

array([[ 4,  6, 11],
       [ 9, 12,  9]])

In [9]:
np.subtract(A,B)

array([[-2, -2, -1],
       [ 3,  4, -3]])

In [11]:
np.multiply(A,B)

array([[ 3,  8, 30],
       [18, 32, 18]])

In [12]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.83333333],
       [2.        , 2.        , 0.5       ]])

In [14]:
np.power(A,2)

array([[ 1,  4, 25],
       [36, 64,  9]])

In [15]:
np.power(A,B)

array([[    1,    16, 15625],
       [  216,  4096,   729]])

In [ ]:
# Condition and Statement

In [2]:
import numpy as np

x = np.array([ i for i in range(10)])

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [5]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [7]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [3]:
import numpy as np

arr = np.array([[1,2,3],[3,4,5],[5,6,7]])

In [4]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [7]:
x = np.amin(arr)
print(x)

1


In [9]:
np.amin(arr, axis=0)

array([1, 2, 3])

In [11]:
np.amin(arr, axis=1)

array([1, 3, 5])

In [13]:
y = np.max(arr)
print(y)

7


In [14]:
np.amax(arr, axis=0)

array([5, 6, 7])

In [16]:
np.amax(arr, axis=1)

array([3, 5, 7])

In [18]:
z = np.median(arr)
print(z)

4.0


In [19]:
r= np.mean(arr)
print(r)

4.0


In [21]:
s = np.std(arr)

In [23]:
print(s)

1.8257418583505538


In [24]:
t = np.var(arr)
print(t)

3.3333333333333335


In [26]:
u = np.percentile(arr , 50)
print(u)

4.0


In [27]:
deg = np.array([0,30,45,60,90])

In [28]:
np.sin(deg*np.pi/100)

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [29]:
np.cos(deg*np.pi/100)

array([ 1.        ,  0.58778525,  0.15643447, -0.30901699, -0.95105652])

In [30]:
np.tan(deg*np.pi/100)

array([ 0.        ,  1.37638192,  6.31375151, -3.07768354, -0.3249197 ])

In [31]:
'''
arcsin
arccos
arctan
'''

'\narcsin\narccos\narctan\n'

In [33]:
arr = np.array([0.5,0.8,-2.1,-9.87])

In [37]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [38]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])


- pd.read_csv : csv
- pd.to_csv : csv
- np.genfromtxt : csv
- np.loadfromtxt : csv
- np.save : npy
- np.load : npy

# Methods
1. Writing json
2. reading json
3. writing excel
4. reading excel
5. writing gzip files
6. reading gzip files

In [39]:
import pandas as pd

In [42]:
with open('sample_file.csv', 'w') as file:
    file.write('Name,Age,Gender\n')
    file.write('Rahul,20,Male\n')
    file.write('Priya,21,Female\n')
    file.write('Amit,22,Male\n')

In [43]:
df = pd.read_csv('sample_file.csv')

In [44]:
df.head()

,Name,Age,Gender
0,Rahul,20,Male
1,Priya,21,Female
2,Amit,22,Male


In [45]:
df.to_json('sample_file_json.json')

In [49]:
df = pd.read_json('sample_file_json.json')

In [50]:
df

,Name,Age,Gender
0,Rahul,20,Male
1,Priya,21,Female
2,Amit,22,Male


In [61]:
%pip install openpyxl


   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpy

In [63]:
df.to_excel('sample_file_excel.xlsx', index=False)

In [65]:
with open('sampleExcelFile.xls', 'w') as file:
    file.write('Name,Age,Gender\n')
    file.write('Rahul,20,Male\n')
    file.write('Priya,21,Female\n')
    file.write('Amit,22,Male\n')

In [67]:
import os

print(os.path.getsize('sampleExcelFile.xls'))


63


In [68]:
%pip install xlrd

Note: you may need to restart the kernel to use updated packages.


In [9]:
import pandas as pd

df = pd.read_csv('sampleExcelFile.csv')

df

,Name,Age,Gender
0,Rahul,20,Male
1,Priya,21,Female
2,Amit,22,Male


In [10]:
df.to_excel('sampleExcelFile.xlsx', index=False)

In [11]:
df2 = pd.read_excel('sampleExcelFile.xlsx')

df2

,Name,Age,Gender
0,Rahul,20,Male
1,Priya,21,Female
2,Amit,22,Male


In [12]:
df.to_csv('samplefilegzio.gz',compression='gzip',index = False)

In [13]:
df = pd.read_csv('samplefilegzio.gz')

In [14]:
df

,Name,Age,Gender
0,Rahul,20,Male
1,Priya,21,Female
2,Amit,22,Male
